### ISSUE TITLE
Exclude block devices from udev scanning

### ISSUE THREAD

**Issue by DemiMarie** [cfcs/qubes-storage-zfs#3]
See https://github.com/QubesOS/qubes-issues/issues/6729

**Comment by ayakael** [comment]
Following DemiMarie's suggestion, I went ahead in creating a udev rule that excludes block devices associated with VMs:
ACTION!="remove", SUBSYSTEM=="block", KERNEL=="zd*",  PROGRAM="/lib/udev/zvol_id %k", RESULT=="*/vm*|*/import*|*/encryption/vm*|*/encryption/import*", ENV{DM_UDEV_DISABLE_DISK_RULES_FLAG}="1", ENV{UDEV_DISABLE_PERSISTENT_STORAGE_RULES_FLAG}="1"

I also added the following to remove by nvme system drives from being detected:
ACTION!="remove", SUBSYSTEM=="block", KERNEL=="nvme*", ENV{DM_UDEV_DISABLE_DISK_RULES_FLAG}="1", ENV{UDEV_DISABLE_PERSISTENT_STORAGE_RULES_FLAG}="1"

Keep in mind that I have no tested the first udev, as I have a different configuration. My zdevs are under */s/vm* rather than */vm* as my encrypted prefix for my whole ZFS system is under the s prefix. I thus changed your python files to reflect that prefix. I have thus not tested this to your zfs_encryption driver as I do not use it as of now. My udev as it is in my system is the following:
ACTION!="remove", SUBSYSTEM=="block", KERNEL=="zd*",  PROGRAM="/lib/udev/zvol_id %k", RESULT=="rpool/s/vm*|rpool/s/import*", ENV{DM_UDEV_DISABLE_DISK_RULES_FLAG}="1", ENV{UDEV_DISABLE_PERSISTENT_STORAGE_RULES_FLAG}="1"

**Comment by cfcs** [comment]
Well done for figuring out the udev stuff --- I tried and did not come up with rules I felt comfortable committing.

What's the rationale for the `prefix/s/vm`  rather than `prefix/vm` ?
Currently `zfs_ns` is generated automatically; we could add a `/s/` to that if there's a good generally valid reason.

Maybe we could just phrase the glob so it covers both, ie something like `KERNEL=="zd*",RESULT="*/vm/*|*/import/*"` ?

or even just something like `*/private|*/volatile|*/root` to cover general volumes? (That feels a bit more hacky)

**Comment by cfcs** [comment]
@ayakael I experimented a bit, working off your commit. Do you think my version will work for your use case?

**Comment by cfcs** [comment]
There's a commented-out section that matches "zfs_member", I think this should cover your nvme device, but I wasn't sure if we wanted to ignore that. Can you see if that works for your nvme device (which is zdev but not a zvol, I'm assuming?)

My procedure for testing ended up being:
```
sudo udevadm control --reload-rules
# either
# sudo udevadm trigger --action=change /dev/zd416
# or:
sudo zfs set volmode=off foo/bar/private
sudo zfs set volmode=default foo/bar/private
```

I found this useful when writing the rules (to see the attributes):
```
sudo udevadm info -e | less
# E: FOO=bar
# ^-- accessible through ENV{FOO}
# S: bla/baz
# ^-- accessible through SYMLINK
```

**Comment by cfcs** [comment]
@ayakael BTW, I think I understand the `/s/` thing now, it's because you want to use the zroot for other things?

I think that is supported by using zfs_encrypted with `-o zpool_name=zroot/s`, but I do not remember if you can give a `zfs_zvol` pool a `zpool_name` option. That should probably be supported to allow namespacing things.

If that is the case, let us open another issue to track that feature?
